@hostname = localhost
@port = 3003
@host = {{hostname}}:{{port}}

###
# @name createCustomer
POST http://{{host}}/customers HTTP/1.1
Content-Type: application/json

{
    "name": "Josimar Zimermann",
    "email": "josimarz@yahoo.com.br"
}

###
# @name listCustomers
GET http://{{host}}/customers HTTP/1.1

###
# @name findCustomer
GET http://{{host}}/customers/{{createCustomer.response.body.$.id}} HTTP/1.1

###
# @name updateCustomer
PUT http://{{host}}/customers/{{createCustomer.response.body.$.id}} HTTP/1.1
Content-Type: application/json

{
    "name": "Ana Ivanovic",
    "email": "ivanovic@wta.com"
}

###
# @name deleteCustomer
DELETE http://{{host}}/customers/{{createCustomer.response.body.$.id}} HTTP/1.1

###
# @name createAccount
POST http://{{host}}/customers/{{createCustomer.response.body.$.id}}/accounts HTTP/1.1

###
# @name listCustomerAccounts
GET http://{{host}}/customers/{{createCustomer.response.body.$.id}}/accounts HTTP/1.1

###
# @name deposit
POST http://{{host}}/accounts/{{createAccount.response.body.$.id}}/deposit HTTP/1.1
Content-Type: application/json

{
    "amount": 999.9
}

###
# @name withdraw
POST http://{{host}}/accounts/{{createAccount.response.body.$.id}}/withdraw HTTP/1.1
Content-Type: application/json

{
    "amount": 100.0
}

###
# @name createTransaction
POST http://{{host}}/transactions HTTP/1.1
Content-Type: application/json

{
    "from": "4dfe3774-a266-4a0c-9abf-f957b1928220",
    "to": "a26da5a9-82ce-40b8-a323-9fa3003b2d88",
    "amount": 10.0
}