@hostname = localhost
@port = 3003
@host = {{hostname}}:{{port}}

###
# @name showAccountBalance
GET http://{{host}}/balances/7d03f050-3ac2-11ee-82c6-0242ac120004 HTTP/1.1

###
# @name createCustomer
POST http://{{host}}/customers HTTP/1.1
Content-Type: application/json

{
    "name": "Josimar Zimermann",
    "email": "josimarz@yahoo.com.br"
}

###
# @name listCustomers
GET http://{{host}}/customers HTTP/1.1

###
# @name findCustomer
GET http://{{host}}/customers/46538e77-39e2-11ee-aa43-0242ac180002 HTTP/1.1

###
# @name updateCustomer
PUT http://{{host}}/customers/46538e77-39e2-11ee-aa43-0242ac180002 HTTP/1.1
Content-Type: application/json

{
    "name": "Ana Ivanovic",
    "email": "ivanovic@wta.com"
}

###
# @name deleteCustomer
DELETE http://{{host}}/customers/46538e77-39e2-11ee-aa43-0242ac180002 HTTP/1.1

###
# @name createAccount
POST http://{{host}}/customers/46538e77-39e2-11ee-aa43-0242ac180002/accounts HTTP/1.1

###
# @name listCustomerAccounts
GET http://{{host}}/customers/7cff3e3f-3ac2-11ee-82c6-0242ac120004/accounts HTTP/1.1

###
# @name deposit
POST http://{{host}}/accounts/46538e77-39e2-11ee-aa43-0242ac180002/deposit HTTP/1.1
Content-Type: application/json

{
    "amount": 999.9
}

###
# @name withdraw
POST http://{{host}}/accounts/46538e77-39e2-11ee-aa43-0242ac180002/withdraw HTTP/1.1
Content-Type: application/json

{
    "amount": 100.0
}

###
# @name createTransaction
POST http://{{host}}/transactions HTTP/1.1
Content-Type: application/json

{
    "from": "7cffdd21-3ac2-11ee-82c6-0242ac120004",
    "to": "7d03f050-3ac2-11ee-82c6-0242ac120004",
    "amount": 500.0
}